
#include "tsch/tsch.h"
#include "tsch/tsch-types.h"

/*TSCH Timeslot Build - Crafted for SF7 as default, must be handcrafted otherwise*/
#ifdef TSCH_SX1272_TIMESLOT_CONF_CCA_OFFSET
#define TSCH_SX1272_TIMESLOT_CCA_OFFSET TSCH_SX1272_TIMESLOT_CONF_CCA_OFFSET
#else
#define TSCH_SX1272_TIMESLOT_CCA_OFFSET 0/*We don't do cca atm*/
#endif

#ifdef TSCH_SX1272_TIMESLOT_CONF_CCA
#define TSCH_SX1272_TIMESLOT_CCA_OFFSET TSCH_SX1272_TIMESLOT_CONF_CCA
#else
#define TSCH_SX1272_TIMESLOT_CCA 0/*We don't do cca atm*/
#endif

#ifdef TSCH_SX1272_TIMESLOT_CONF_TX_OFFSET
#define TSCH_SX1272_TIMESLOT_TX_OFFSET TSCH_SX1272_TIMESLOT_CONF_TX_OFFSET
#else
#define TSCH_SX1272_TIMESLOT_TX_OFFSET 7000
#endif

#ifdef TSCH_SX1272_TIMESLOT_CONF_RX_OFFSET
#define TSCH_SX1272_TIMESLOT_RX_OFFSET TSCH_SX1272_TIMESLOT_CONF_RX_OFFSET
#else
#define TSCH_SX1272_TIMESLOT_RX_OFFSET 5000
#endif

#ifdef TSCH_SX1272_TIMESLOT_CONF_RX_ACK_DELAY
#define TSCH_SX1272_TIMESLOT_RX_ACK_DELAY TSCH_SX1272_TIMESLOT_CONF_RX_ACK_DELAY
#else
#define TSCH_SX1272_TIMESLOT_RX_ACK_DELAY 4000
#endif

#ifdef TSCH_SX1272_TIMESLOT_CONF_TX_ACK_DELAY
#define TSCH_SX1272_TIMESLOT_TX_ACK_DELAY TSCH_SX1272_TIMESLOT_CONF_TX_ACK_DELAY
#else
#define TSCH_SX1272_TIMESLOT_TX_ACK_DELAY 5000
#endif

#ifdef TSCH_SX1272_TIMESLOT_CONF_RXWAIT
#define TSCH_SX1272_TIMESLOT_RXWAIT TSCH_SX1272_TIMESLOT_CONF_RXWAIT
#else
#define TSCH_SX1272_TIMESLOT_RXWAIT 4000
#endif
#ifdef TSCH_SX1272_TIMESLOT_CONF_ACKWAIT
#define TSCH_SX1272_TIMESLOT_ACKWAIT TSCH_SX1272_TIMESLOT_CONF_ACKWAIT
#else
#define TSCH_SX1272_TIMESLOT_ACKWAIT 2000
#endif

#ifdef TSCH_SX1272_TIMESLOT_CONF_RXTX
#define TSCH_SX1272_TIMESLOT_RXTX TSCH_SX1272_TIMESLOT_CONF_RXTX
#else
#define TSCH_SX1272_TIMESLOT_RXTX 0/*This is obsolete in TSCH Source*/
#endif

#ifdef TSCH_SX1272_TIMESLOT_CONF_MAXACK
#define TSCH_SX1272_TIMESLOT_MAXACK TSCH_SX1272_TIMESLOT_CONF_MAXACK
#else
#define TSCH_SX1272_TIMESLOT_MAXACK 50000/*Assuming 17-byte acks*/
#endif

#ifdef TSCH_SX1272_TIMESLOT_CONF_MAXTX
#define TSCH_SX1272_TIMESLOT_MAXTX TSCH_SX1272_TIMESLOT_CONF_MAXTX
#else
#define TSCH_SX1272_TIMESLOT_MAXTX 400000
#endif

#ifdef TSCH_SX1272_TIMESLOT_CONF_TIMESLOTLENGTH
#define TSCH_SX1272_TIMESLOT_TIMESLOTLENGTH TSCH_SX1272_TIMESLOT_CONF_TIMESLOTLENGTH
#else
#define TSCH_SX1272_TIMESLOT_TIMESLOTLENGTH 490000
#endif


const tsch_timeslot_timing_usec tsch_timeslot_timing_sx1272 = {
  TSCH_SX1272_TIMESLOT_CCA_OFFSET, /* CCAOffset */
  TSCH_SX1272_TIMESLOT_CCA_OFFSET, /* CCA */
  TSCH_SX1272_TIMESLOT_TX_OFFSET, /* TxOffset */
  TSCH_SX1272_TIMESLOT_RX_OFFSET, /* RxOffset */
  TSCH_SX1272_TIMESLOT_RX_ACK_DELAY, /* RxAckDelay */
  TSCH_SX1272_TIMESLOT_TX_ACK_DELAY, /* TxAckDelay */
  TSCH_SX1272_TIMESLOT_RXWAIT, /* RxWait */
  TSCH_SX1272_TIMESLOT_ACKWAIT, /* AckWait */
  TSCH_SX1272_TIMESLOT_RXTX, /* RxTx */
  TSCH_SX1272_TIMESLOT_MAXACK, /* MaxAck */
  TSCH_SX1272_TIMESLOT_MAXTX, /* MaxTx */
  TSCH_SX1272_TIMESLOT_TIMESLOTLENGTH /* TimeslotLength */
};




